name: Coverity Detailed Workflow for Advanced Users
                                                                                                                                                                                                                                         
on:
  push:
    branches: [main, master, develop, stage, release]
  pull_request:
    branches: [main, master, develop, stage, release]

jobs:
  coverity-scan:
    runs-on: [ mac-arm-sh ]
    
    defaults:
      run:
        working-directory: ${{ github.workspace }}/nodejs-npm

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Specify Node version
   
    - name: Install dependencies
      run: npm install  

    - name: Build Project
      run: |
        npm rebuild

    - name: Coverity Full Scan
      id: coverity-full-scan
      if: ${{ github.event_name != 'pull_request' }}
      uses: blackduck-inc/black-duck-security-scan@v2
      
      with:
        ### SCANNING: Required fields
        coverity_url: ${{ secrets.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}

        ### BREAKING THE BUILD
        # coverity_policy_view: 'Outstanding Issues'
        
        ### Uncomment below configuration if Bridge diagnostic files needs to be uploaded
        # include_diagnostics: true

        ### Mark build status if policy violating issues are found
        mark_build_status: 'success'
      
    - name: Coverity PR Scan
      id: coverity-pr-scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: blackduck-inc/black-duck-security-scan@v2
      with:

        ### SCANNING: Required fields
        coverity_url: ${{ secrets.COVERITY_URL }}
        coverity_user: ${{ secrets.COVERITY_USER }}
        coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
  
        ### PULL REQUEST COMMENTS:
        coverity_prComment_enabled: true
        coverity_prComment_impacts: 'High,Medium,Low,Audit'
        # Required when PR comments is enabled
        github_token: ${{ secrets.GITHUB_TOKEN }} 

        ### Arbitrary product-related CL arguments
        coverity_clean_command: "npm cache clean --force"
        coverity_build_command: "npm install"
        
        ### Mark build status if policy violating issues are found
        mark_build_status: 'success'
        
